### ISSUE TITLE
Prepare for 2.3.0 Release

### ISSUE THREAD

**Issue by willingc** [nteract/bookstore#96]
Some tasks to do before 2.3.0 release:

- [x] Add Python unit tests (aim for 50% coverage for this release and increase in following releases)
- [x] Add an API document #95 
- [x] PR #89 Misc fixes
- [x] PR #90 Python files
- [x] PR #91 Version check test. Assigned to @willingc
- [x] PR #88 JS fixes
- [x] Update changelog

cc/ @mpacer @MSeal @rgbkrk

**Comment by MSeal** [comment]
@mpacer and I got started on the unit testing front. M's going to finish that up but we should have a better setup now for testing the async handlers moving forward.

**Comment by willingc** [comment]
Let's work on the changelog and then :shipit:

**Comment by mpacer** [comment]
With the three PRs that are open now it should bring the overall code-base to 84% test coverage.

More importantly, it's far better documented and way more readable.

I'll work on the changelog assuming that those 3 PRs will be merged. It changes a few of the APIs, but fortunately we now have API docs so its clear what exactly changed! Huzzah!

**Comment by mpacer** [comment]
Released! 

Closing thanks all!
